### PR TITLE
Fix apk build error by upgrading build.gradle

### PR DESCRIPTION
**Pull request by ochrin**
# Upgrade build.gradle to fix errors when trying to generate apk

When trying to generate apk with following commands:
```
cd android
./gradlew clean
./gradlew assembleRelease
```
The following errors appear:
```
Execution failed for task ':@react-native-community_checkbox:verifyReleaseResources'.
> 1 exception was raised by workers:
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  error: resource android:style/TextAppearance.Material.Widget.Button.Borderless.Colored not found.
  error: resource android:style/TextAppearance.Material.Widget.Button.Colored not found.
  /media/jenkins/workspace/air_app_nightly_build/node_modules/@react-native-community/checkbox/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
  /media/jenkins/workspace/air_app_nightly_build/node_modules/@react-native-community/checkbox/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
...
```

## Test Plan

Tested with RN 0.61. 

### What's required for testing ?
```
cd android
./gradlew clean
./gradlew assembleRelease
```
## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

Not tested on iOS as checkbox is not supposed to work on iOS.

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by KimGames** [comment]
I'm having some problems to generate release apk

**Comment by KimGames** [comment]
* What went wrong:
Could not determine the dependencies of task ':@react-native-community_netinfo:compileReleaseRenderscript'.
> Could not resolve all dependencies for configuration ':@react-native-community_netinfo:releaseCompileClasspath'.
   > Could not determine artifacts for androidx.core:core:1.0.1: Skipped due to earlier error

**Comment by ochrin** [comment]
Do you mean you have problem generating your apk with the current release of checkbox or with this pull request?

**Comment by KimGames** [comment]
With the current release of checkbox

**Comment by ochrin** [comment]
Not sure it will work but can you try to modify the `build.gradle` file in `node_modules/...checkbox/android/build.gradle` the way it is modified in this commit and tell us if it solves your issue?

**Comment by ochrin** [comment]
And why do you think it is linked to checkbox? You error seems to be linked to netinfo...

**Comment by Jnlbr** [comment]
I'm having this same error

**Comment by nicholaslee119** [comment]
the failure of android-compile because of the limit of CI.
I test the `android-compile` locally, it was OK!

**Comment by ochrin** [comment]
Thanks for merging  :+1:

**Pull request merged**
